apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygohello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mygohello
  template:
    metadata:
      labels:
        app: mygohello
    spec:
      containers:
        - name: mygohello
          image: amitrane04/mygohello:latest
          ports:
          - containerPort: 8888
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "20Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 3
