apiVersion: v1
kind: Service
metadata:
  name: mygohello
  labels:
    app: mygohello
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: mygohello
  type: ClusterIP
