apiVersion: v1
kind: Pod
metadata:
        name: kuardvol
spec:
        volumes:
                - name: "kuard-data"
                  hostPath:
                          path: "/home/krawler/K8s/k8-data/kvoltest"
        containers:
                - image: gcr.io/kuar-demo/kuard-amd64:blue
                  name: kuardvol
                  volumeMounts:
                          - mountPath: "/data"
                            name: "kuard-data"
                  ports:
                          - containerPort: 8080
                            name: http
                            protocol: TCP
