apiVersion: v1
kind: Pod
metadata:
  name: mytomcat
spec:
  containers:
    - image: amitrane04/mytomcat
      name: mytomcat
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
